### ISSUE TITLE
Getting yii\\elasticsearch\\Connection::clients

### ISSUE THREAD

**Issue by foziazahoor** [mikemadisonweb/yii2-elasticsearch#1]
I'm getting this error

> "name": "Unknown Property",
    "message": "Setting unknown property: yii\\elasticsearch\\Connection::clients",

**Comment by mikemadisonweb** [comment]
Hello, could you please provide more info about your problem?
The reason why I ask is that yii\elasticsearch\Connection is not a part of this extension, it's an official Yii2 Elasticsearch extension. This one is more focused on latest versions of Elasticsearch and it do not use official package in any way.

**Comment by foziazahoor** [comment]
Hi,

Yeah it was my mistake. I didn't set config/main.php as per documentation. But when i followed instructions then i did not get any error.

Thanks
