### ISSUE TITLE
Global search over indexes or mappings

### ISSUE THREAD

**Issue by michaelarnauts** [mikemadisonweb/yii2-elasticsearch#3]
There seems to be no way to search over indexes (`_all` index) or in all types. If no type is specified, the default type is being used. The `_all` index is rejected.

```php
        /** @var \mikemadisonweb\elasticsearch\Configuration $elastic */
        $elastic = Yii::$app->elasticsearch;

        /** @var \mikemadisonweb\elasticsearch\components\Finder $finder */
        $finder = $elastic->getFinder('_all', null);
```

throws:

```
Exception 'TypeError' with message 'Argument 1 passed to mikemadisonweb\elasticsearch\Configuration::getDefaultMapping() must be of the type array, boolean given, called in /opt/app/vendor/mikemadisonweb/yii2-elasticsearch/Configuration.php on line 77'
```

Even when specifying the correct index, it still needs a specific mapping type.
```
Exception 'yii\base\InvalidConfigException' with message '`` mapping is not configured'
```

**Comment by mikemadisonweb** [comment]
Hi Michael, 
Thanks for figuring that out. Yes, I agreed that the definition should be changed to include "search all mappings" and "search all indexes" use-cases, but unfortunately, I don't have enough time at the moment. I will put that on my list.

**Comment by mikemadisonweb** [comment]
Added to version 1.2.1:
https://github.com/mikemadisonweb/yii2-elasticsearch/commit/13ccaa4cd9364d336cff56b9cd38f51eaed99c6b
There is no need to pass `_all`, just don't provide any arguments to search among all indexes and mappings: $finder = $elastic->getFinder();
